services:
  # MongoDB services
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db

  # NodeJS Services
  api: 
    build: .
    ports:
      - 3005:3000
    volumes:
      - .:/usr/src/app  
    environment: 
        PORT: 3004
        staging: test
        MONGO_USER: tshubham0111
        MONGO_ATLAS_PW: s7c520YAfRG4YK6Z
        MONGO_CLUSTER: cluster0.siksoww.mongodb.net
        DB_NAME: flagright
        DB_USERNAME: tshubham0111
        JWT_SECRET: 9af9dfc9b7cbe685c63db27d64962d3a09abfb59ccd6bc86c9ef93ec6a0fdef13cec6e44b79685d5e0d928271c1495ce7975241b5b211ce9319c6ffe1c1834d3c
        HOST_URL: http://localhost:3004/api/v1
    depends_on:
      - mongodb      

volumes:
  mongodb: {}